### ISSUE TITLE
what happen if you price service take a day to respond?

### ISSUE THREAD

**Issue by nhe150** [gvolpe/pricer-fs2-demo#1]
How you are going to plan to remedy a long running pricing service?

**Comment by gvolpe** [comment]
> what happen if you price service take a day to respond?

Then you will need to consider to fire the people that wrote that service... XD

Seriously, what I would do is just to split the call to the pricer service in the same way the storage is implemented, so then you will have three parallel streams and you can keep consuming and persisting messages but only when pricer service returns back a response they will be published. It should look like this:

```
fs2.concurrent.join(3)(
      Stream(
        consumer      observe logger to storage.write,
        storage.read  to pricer.write,
        pricer.read   to publisher
      )
 )
```

PricerService should be implemented as the Storage (an Exchange in Scalaz Streams).

Cheers,
Gabriel.

**Comment by nhe150** [comment]
I like that joke: )

I am most dealing with large data map-reduce kind of task scheduling. 10% of  the tasks usually took quite long(in days), 90% take a couple of seconds. 

How concurrent are the fs2.concurrent.join()?

**Comment by nhe150** [comment]
Would you please provide a build.sbt?

**Comment by gvolpe** [comment]
I invite you to check this project out and try it yourself, you'll find the build.sbt as part of this demo.

Watch [this video](https://www.youtube.com/watch?v=8YxcB6PIUDg&list=PLFrwDVdSrYE6PVD_p6YQLAbNaEHagx9bW&index=3) of Michael Pilquist explaining concurrency in FS2, including the join function. But summing up, it works with n streams and the number 3 in the example above means the concurrent number of open streams you want to have.

Take a look at the [signature](https://github.com/functional-streams-for-scala/fs2/blob/series/0.9/core/src/main/scala/fs2/concurrent.scala#L40).

Cheers,
Gabriel.
